version: "3.8"
services:
  node:
    build: .
    env_file: ./.env
    command: npm start
    volumes:
      - .:/app/
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on: 
      - mysqldb
    environment: 
      MYSQL_HOST: mysqldb
  mysqldb:
    image: mysql:5.7
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - ./src/learn/config/mysql.conf.d :/etc/mysql/mysql.conf.d
      - ./src/learn/files:/app/
  mysql_workbench:
    image: lscr.io/linuxserver/mysql-workbench
    container_name: mysql_workbench
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/London
    volumes:
      - mysql_workbench_config:/etc/mysql_workbench
    ports:
      - $MYSQL_WORKBENCH_LOCAL_PORT:$MYSQL_WORKBENCH_DOCKER_PORT
    depends_on: 
      - mysqldb
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
volumes:
    mysql_workbench_config: